### ISSUE TITLE
Provide an example how to attach an external *.d.ts to the editing context

### ISSUE THREAD

**Issue by Artazor** [Microsoft/monaco-typescript#1]
Hi, @alexandrudima! Nice work!

Can you give a brief examples: 

* how to attach custom type information to the editing context.
* what is the best practice for the switching between two documents with different external *.d.ts ?

**Comment by TedDriggs** [comment]
This would be extremely useful for my project. I have objects that I'm going to inject into the environment when the code is executed, and I'd like the user to get Intellisense information about those injected objects without having import or other statements in their source code. If it matters, my users would be specifically writing JS, but we could provide *.d.ts files to the editor without issue.

**Comment by Artazor** [comment]
@TedDriggs nice example!
