### ISSUE TITLE
Formatting options

### ISSUE THREAD

**Issue by pierogitus** [Microsoft/monaco-typescript#3]
This repo has these formatting options set to true.
```
InsertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis: true,
InsertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets: true,
```
Shouldn't they be false to match what VS Code does? Or at least expose the options in the monaco.languages.typescript namespace

**Comment by pelikhan** [comment]
Matching formatting behavior with VS code would be great.
