### ISSUE TITLE
can't reload ExtraLib for LanguageService

### ISSUE THREAD

**Issue by Shpiller** [Microsoft/monaco-typescript#5]
`addExtraLib(content: string, filePath?: string): IDisposable {
		if (typeof filePath === 'undefined') {
			filePath = `ts:extralib-${Date.now()}`;
		}

		if (this._extraLibs[filePath]) {
			throw new Error(`${filePath} already a extra lib`);
		}

		this._extraLibs[filePath] = content;
		this._onDidChange.fire(this);

		return {
			dispose: () => {
				if (delete this._extraLibs[filePath]) {
					this._onDidChange.fire(this);
				}
			}
		};
	}

`
delete this._extraLibs[filePath] return false
and not delete this._extraLibs[filePath]

**Comment by Shpiller** [comment]
is a reason
get extraLibs(): { [path: string]: string; } {
		return Object.freeze(this._extraLibs);
	}

**Comment by jrieken** [comment]
`addExtraList` returns a disposable which unloads on calling `dispose`. Then you can add an updated version of the lib

**Comment by Shpiller** [comment]
I tried dispose. It's didn't work because  get extraLibs() freeze this._extraLibs

**Comment by Shpiller** [comment]
delete this._extraLibs[filePath] because this._extraLibs already frozen

**Comment by jrieken** [comment]
I see. The problem is that someone is accessing `extraLibs` first, effectively freezing the underlying object.
