### ISSUE TITLE
Can I have my custom mylib.d.ts loaded?

### ISSUE THREAD

**Issue by ryanlin1986** [Microsoft/monaco-typescript#6]
This is really great library, give us a lot of possibilities for our own IDE platform.
In my case, I have some dynamically generated d.ts files, which want to be loaded into the monaco-editor,  I don't see the documentation, please give us some hint for doing this.

**Comment by paveldk** [comment]
I know it's a workaround but you can use Monaco.editor.createModel(fileContent, "typescript", dtsUri); You can check #8

**Comment by jrieken** [comment]
No workaround needed. There is `addExtraLib` for this: https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-configure-javascript-defaults
