### ISSUE TITLE
Why is the _extraLibs object Frozen upon first access?

### ISSUE THREAD

**Issue by wiredprairie** [Microsoft/monaco-typescript#7]
When a call to `extraLibs` is made:

    get extraLibs(): { [path: string]: string; } {
		return Object.freeze(this._extraLibs);
    }

It freezes the `_extraLibs` member, which means that it's not modifiable anymore. That seems unusual as it prevents all modifications to that object (the `destroy` won't work and the `addExtraLibs` function doesn't work either). (*Our thought was that someone wanted a frozen clone of the object, but that's not how `freeze` works*).

We worked around the issue with this *hack*:

    Object.defineProperty(
        Object.getPrototypeOf(monaco.languages.typescript.typescriptDefaults),
        "extraLibs", 	{
	    get: function ()	{
                return this._extraLibs;
            }, enumerable: true, configurable: true
    });

Maybe there's a more proper way to add extra content so that declaration files can be resolved, but we couldn't find one.

**Comment by jrieken** [comment]
It's a bug this is in the API. **only** use `addExtraLib`

**Comment by jrieken** [comment]
Well, there is value in being able to see what `extraLibs` there are - no need to break the API

**Comment by wiredprairie** [comment]
There's a very eary call in the lifecycle of the editor:

https://github.com/Microsoft/monaco-typescript/blob/3f5e823039387ed586dc242fc56ca73e01877abf/src/workerManager.ts#L62

Which executes the `freeze` on the `extraLibs` property and prevents all future calls to `addExtraLib` from working. 

My code does actually calls this:

    monaco.languages.typescript.typescriptDefaults.addExtraLib(imports, "my-extra-ts-stuff");

But, it won't work when the associative array structure `_extraLibs` is frozen.

**Comment by jrieken** [comment]
See #5
