### ISSUE TITLE
How can we only show type valid autocompletion options?

### ISSUE THREAD

**Issue by ZombieHippie** [Microsoft/monaco-typescript#9]
In IDEs such as Eclipse, the autocomplete options limit themselves to only options which are technically valid solutions to the editor's position, this would be incredible for learners, and **reduce the amount of** *noise* in the current completion options.

![noisy autocomplete options](https://cloud.githubusercontent.com/assets/2925395/17308201/70bc092c-57fe-11e6-9d6f-2b5d235f5d5b.png)

In this example, the `alert` suggestion is neither a number or returns a number when called, so is there a way to remove it? Or rank suggestions so more fitting global functions such as `parseFloat` appear higher in this list?

**Comment by basarat** [comment]
This request really belongs in Microsoft/TypeScript https://github.com/Microsoft/TypeScript/issues 

Personal opinion : That said, there are concerns like performance and will ask for a proposal e.g. its difficult to know exactly how you might use `foo` e.g. `foo.bar.bax.toSomthing` *might be valid at that position* even if `foo` isn't. So don't think its likely to get any attention their either. Also you might want to `foo` then `makeBar(foo)` and its useful to have autocomplete for `foo` even if none of its access chain is valid  :rose:

**Comment by basarat** [comment]
Ofcourse personal opinions. Please raise there if you feel passionate about it :heart:

**Comment by ZombieHippie** [comment]
Thank you for the reply Basarat, is this feature part of the language
service then?

**Comment by basarat** [comment]
> is this feature part of the language service

Yes :rose:
